#!/usr/bin/env python
# -*- coding: utf-8 -*-
import requests, json, argparse, sys, os
from bs4 import BeautifulSoup

try:
	with open(os.path.join(os.path.dirname(__file__), 'sms_config.json')) as config:
		config = json.load(config)
except IOError, e:
	print "Missing sms_config.json in send_sms.py directory"
	sys.exit(1)

username = config['username']
password = config['password']

def send(receiver, message):
	login_url = 'https://netcom.no/min-side-login?p_auth=4GV3GizE&p_p_id=auth_WAR_authportlet&p_p_lifecycle=1&p_p_state=normal&p_p_mode=view&p_p_col_id=column-1&p_p_col_count=1&_auth_WAR_authportlet_javax.portlet.action=login'
	sms_post_url = 'https://netcom.no/minside/css/ajax/meldingssenter/sms/sms.ajax'
	sms_continue_url = 'https://netcom.no/minside/css/sendsms.html'

	headers = {'Content-Type': 'application/x-www-form-urlencoded; charset=UTF-8'}
	login_data = {'userId': username, 'password': password}

	send_form = {
			'forms_submit_id': 'submitSendsms',
			'numberOfReceivers': 1,
			'gsmnumber': '',
			'groups': 3,
			'message': message,
			'saveMessage': 'true',
			'cocoon-ajax': 'false',
			'validationerror': ''
			}

	number_form = {
			'forms_submit_id': 'submitChooseContact',
			'numberOfReceivers': 0,
			'gsmnumber': receiver,
			'groups': 3,
			'message': '',
			'saveMessage': 'true',
			'cocoon-ajax': 'false',
			'validationerror': ''
			}

	continue_form = {'cocoon-ajax-continue':'true'}

	with requests.session() as s:
		s.headers.update(headers)

		r1=s.post(login_url, data=login_data)
		r2=s.get(sms_continue_url)

		# get 'continiuation-id' from web form
		soup1=BeautifulSoup(r2.content, "html.parser")
		number_form['continuation-id'] = soup1.find("input", {"name": "continuation-id"})['value']
		
		r3=s.post(sms_post_url, data=number_form)

		# get new 'continuation-id' after new page load
		soup2=BeautifulSoup(r3.content, "html.parser")
		last_cid = soup2.find("input", {"name": "continuation-id"})['value']
		send_form['continuation-id'] = last_cid
		continue_form['continuation-id'] = last_cid
		
		r4=s.post(sms_post_url, data=send_form)
		r5=s.post(sms_continue_url, data=continue_form)
		print "The following message was sent to {}:".format(receiver)
		print message

def main():
	parser = argparse.ArgumentParser(description='Send sms message through Netcom website')
	parser.add_argument('-n','--number', help='Phone number of receiver',required=True)
	parser.add_argument('-m','--message',help='Message to be sent', required=True)
	args = parser.parse_args()

	send(args.number, args.message)


if __name__ == "__main__":
	main()
