alias borudweb='ssh -l andebor borudweb.com'
alias gina='ssh -l andebor gina.it.ntnu.no'
alias poseidon='ssh -l andebor poseidon.orakel.ntnu.no'
alias hades='ssh -l andebor hades.orakel.ntnu.no'
alias macgyver=' ssh -l andebor borud.eu'
alias rambo='ssh -l andebor andersborud.com'
alias fgdrifttest='ssh -l andebor -p 2223 borud.eu'
alias privattest='ssh -l andebor -p 2222 borud.eu'
alias calypso='ssh -l andebor calypso.orakel.ntnu.no'
alias showHidden='defaults write com.apple.finder AppleShowAllFiles YES; killall Finder /System/Library/CoreServices/Finder.app'
alias hideHidden='defaults write com.apple.finder AppleShowAllFiles NO; killall Finder /System/Library/CoreServices/Finder.app'
alias mountDO='sshfs andebor@andersborud.com:/var/www/ /Users/andebor/web-dev/remote-mount/ -ocache=no'
alias mountFOLK='sshfs andebor@login.stud.ntnu.no:/web/folk/andebor web-dev/folk-mount/'
