alias borudweb='ssh andebor@$ROCKY'
alias gina='ssh andebor@$GINA'
alias poseidon='ssh andebor@$POSEIDON'
alias macgyver=' ssh andebor@$MACGYVER'
alias rambo='ssh andebor@$RAMBO'
alias fgdrifttest='ssh -p 2223 andebor@$MACGYVER'
alias privattest='ssh -p 2222 andebor@$MACGYVER'
alias calypso='ssh andebor@$CALYPSO'
alias showHidden='defaults write com.apple.finder AppleShowAllFiles YES; killall Finder /System/Library/CoreServices/Finder.app'
alias hideHidden='defaults write com.apple.finder AppleShowAllFiles NO; killall Finder /System/Library/CoreServices/Finder.app'
alias mountDO='sshfs andebor@$RAMBO:/var/www/ /Users/andebor/web-dev/remote-mount/ -ocache=no'
alias mountFOLK='sshfs andebor@$STUD:/web/folk/andebor web-dev/folk-mount/'
alias vm='ssh andebor@$VM'
alias atlas='ssh -p 2469 andebor@$ATLAS'
alias stud='ssh andebor@$STUD'
alias publicip='curl http://api.ipify.org'
